### ISSUE TITLE
Make change of mode visible

### ISSUE THREAD

**Issue by gitsamhub** [neverwinter-nights/Mesh-Selection-Mode-Cycle#1]
Addon works as expected. However, It does not show changed selection mode in object.

e.g. In default Blender hotkey if i press (1), then vertex points are visible on active object mesh
Also, If i press (2), then It highlights edges.

That way It is much easy to know which mode is active without looking at header icons.

**Comment by neverwinter-nights** [comment]
Yes. At the moment the only thing that this add-on does is the change of the selected mesh selection mode.
I will examine if it is possible to convert the selection (selected entities) into vertices, edges or faces with a script.

**Comment by neverwinter-nights** [comment]
I have fixed this issue by using a high level API. 
Please, check the version 1.1 and confirm if it works.

**Comment by gitsamhub** [comment]
Hi, 
The updated version is working nicely.
Thank you for your quick response. 

PS: This is probably out of context but Is it possible to change the color or tone of edges while switching to edge mode? 
It is just that default edge and face mode looks almost the same. Nothing to do with this add-on off course.

**Comment by neverwinter-nights** [comment]
Hello,
Thanks for the response.

Well, this is a feature of Blender as far as I know. I do not know whether it is customizable.
